dist: xenial
language: python
python:
- 3.8-dev
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: burnnat
  password:
    secure: GNz5jI/7EmyCsVR0gYXIzZv8WtRGNiI/Vp1IHaSb+AX2ocStg2wJ6aHkIWA4Z28vnsdIrStMtJiYQ/LDyC/MqRTTIR6v66pwXDktp4fm1Mp5zZYLlEvEz8qFkdisSyKcbrCMK6qhw2y1+BLsBDNVaPuefJRjUXZQaophfz5BPyvilsAPUkGHA6RzlAtKJJAn70fxIMEVjiTfFrXhwf3bHe4Zpe0N6csVXnUOYzQ4OMxyAqXGfTrYcMrxQanfXppgiQjrgPkJvL922FiEec4eAdNubaKzblMloM/MQExcnti2Fbc11AinrpgFsCQ3Xs1gB7NyU1BlzfDnAdr3YVUhN3gWiLUEX9GXAJiRqvjDOS/Y33/VzSDlg9tzVxCXbbPJSljnx5eNs+pe286Qz7NhZymIj3DBzIpAeo9GE3Petr30lKyV4MBotGcGbl4fP4+SpabCg8TWxJg+EadQuYdaTTKvBv2mhd8RNN6ld2eY/iwmfgjqaINgyzXUVoEy8EqqpKnanhsXF6eiHx6qp542+v1+HVio8j/Pz8G+KsWvL1JUt2lZIy8AqauSFNXmDP2qaSeJLipWGP0s/VLrKBUi71Dj6eLOM3+Arh2FSCZ/OV1Reon3dfHjpRbn4OTOH0sD6XeHoU49ZN6von22Kpm34HnIzDgnW/Xa4SrhYhMB2Ws=
  on:
    tags: true
    repo: burnnat/screenly_ose
    python: 3.7
